name: Download EPG

on:
  push:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam sekali (untuk fleksibilitas)

jobs:
  download_epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Check WIB time
      id: check_time
      run: |
        CURRENT_HOUR=$(TZ='Asia/Jakarta' date +'%H')
        if [ "$CURRENT_HOUR" -eq "00" ]; then
          echo "Time matches 00:00 WIB. Proceeding..."
          echo "run_script=true" >> $GITHUB_ENV
        else
          echo "Not 00:00 WIB. Skipping..."
          echo "run_script=false" >> $GITHUB_ENV

    - name: Run script
      if: env.run_script == 'true'
      run: |
        python pegsc.py
        echo "Last updated: $(date)" >> epg_metadata.txt

    - name: Commit and push changes
      if: env.run_script == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet || git commit -m "Update EPG file on $(date)"
        git push
